# -*- coding: utf-8 -*-
"""FlightPricePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14iYXhU9dUz4S88IcYYxp9H2M0GoPH_ny
"""

# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

# Load the data
df = pd.read_csv('/Clean_Dataset.csv')

# Print the data
print('Dataset Loaded. Shape', df.shape)
print(df.head(5))

# Handle Categorical Columns
from sklearn.preprocessing import LabelEncoder

label_encoder = {}
# Go through all of the columns that contain words/text
for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoder[col] = le

# Features and Target
X = df.drop('price', axis = 1)
Y = df['price']

# Split the data into training and testing datta sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, shuffle = True, random_state = 42)

# Create and train the model
model = RandomForestRegressor(
    n_estimators = 300,
    random_state = 42
)

# Train the model
model.fit(X_train, Y_train)

# Predict the test values
predictions = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(Y_test, predictions)
r2 = r2_score(Y_test, predictions)

print('Models Performance:')
print('MSE', mse)
print('r^2:', r2)

# Print the predictions
comparison = pd.DataFrame(
    {
        "Actual Price": Y_test.values[:20],
        "Predicted Price": predictions[20]
    }
)

print('Sample Predictions:')
print(comparison)

# Plot the actual values with the predicted values
plt.figure(figsize=(12,6))
plt.plot(Y_test.values[:100], label = 'Actual Prices', color = 'blue', linestyle = '--')
plt.plot(predictions[:100], label = 'Predicted Prices', color = 'orange', linestyle = '--')
plt.title('Flight Price Prediction - Actual vs Predicted')
plt.xlabel('Sample Index')
plt.ylabel('Price')
plt.legend
plt.show()